# Generated by Django 5.2.7 on 2025-10-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_palindrome', models.BooleanField()),
                ('unique_characters', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('sha256_hash', models.CharField(max_length=200)),
                ('character_frequency_map', models.JSONField(default=dict)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.string')),
            ],
        ),
    ]
