# Generated by Django 5.2.7 on 2025-10-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='String',
            new_name='Sentence',
        ),
    ]
