# Generated by Django 5.2.7 on 2025-10-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_string_sentence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='value',
            new_name='sentence',
        ),
    ]
