# Generated by Django 5.2.7 on 2025-10-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_value_properties_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
